import Head from 'next/head'
import React, {useEffect, useState} from "react";
import moment from "moment";

import 'bootstrap/dist/css/bootstrap.css';
import Link from "next/link";
import Image from "next/image";
import {useAuth, useUser} from "@/context/authContext";
import {http} from "@/utils/http";
import {getUserFromCookie} from "@/utils/Cookies";
import CardImagemButton from "@/components/cards/CardImagemButton";
import CardDashBoard from "@/components/cards/CardDashBoard";


export default function Home() {

    const [usuario, setUsuario] = useState('');

    useEffect(() => {
        setUsuario(getUserFromCookie())
    }, [usuario])


    const {user, logout} = useAuth();

    const hoje = moment().format('YYYY-MM-DD')
    const dataAtual = moment().format('DD-MM-YYYY')
    const mes = moment().format('MM')

    const [receitas, setReceitas] = useState([]);
    useEffect(() => {
        http.get(`/receitasLista`, {
            headers: {
                Authorization: `Bearer ${localStorage.getItem("token")}`
            }
        })
            .then((response) => {
                setReceitas(response.data)
            })
            .catch((error) => {
                console.error("Erro ao buscar a lista de receitas", error)
            });
    }, []);

    const [despesas, setDespesas] = useState([]);

    useEffect(() => {
        http.get(`/despesaslista`,
            {
                headers: {
                    Authorization: `Bearer ${localStorage.getItem("token")}`
                }
            })
            .then((response) => {
                setDespesas(response.data)
            })
            .catch((error) => {
                console.error("Erro ao buscar a lista de despesas", error)
            });
    }, []);

    //Filtrando dados Receitas - Data Atual
    const receitasDataAtual = receitas.filter((receita) => receita.data_vencimento === hoje && receita.status === "A PAGAR");
    const totalReceitaAtual = receitasDataAtual.length;
    const valorReceitaAtual = receitasDataAtual.reduce((total, receita) => {
        return total + receita.valor
    }, 0)

    //Filtrando dados Receitas - Mes
    const totalReceitaMes = receitas.length;
    const valorReceitaMes = receitas.reduce((total, receita) => {
        return total + receita.valor
    }, 0)


    //FIltrando dados Despesas
    const despesasDataAtual = despesas.filter((receita) => receita.data_vencimento === hoje && receita.status === "A PAGAR");
    const totalAtualDespesas = despesasDataAtual.length;
    const valorDespesaAtual = despesasDataAtual.reduce((total, despesa) => {
        return total + despesa.valor
    }, 0)


    const totalDespesasMes = despesas.length;
    const valorDespesaMes = despesas.reduce((total, despesa) => {
        return total + despesa.valor
    }, 0)


    return (
        <>
            <Head>
                <title>Sistema de Gestão para Microempreendedores</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>

            </Head>
            <main className="d-sm-flex align-items-center">
                <section
                    className="container d-sm-flex flex-sm-column align-items-center justify-content-center pb-5"
                >
                    <h1 className="w-100 text-center">SEJA BEM VINDO(A)</h1>
                    <h3 className="mb-5 text-center">{user}</h3>
                    <p className="fw-bolder text-app-sgme fs-2">Menu Rapido</p>
                    <div className="container-sm d-sm-flex flex-wrap justify-content-between">

                        <CardImagemButton
                            link="/gestao-sgme/clientes/cadastro"
                            img="/img/icone_cad_cliente.svg"
                            titleLink="Novo Cliente"/>

                        <CardImagemButton
                            link="/gestao-sgme/fornecedores/cadastro"
                            img="/img/icone_cad_produto.svg"
                            titleLink="Novo Fornecedor"/>

                        <CardImagemButton
                            link="/gestao-sgme/financeiro/contas-a-pagar/cadastro"
                            img="img/icone_cad_despesa.svg"
                            titleLink="Nova Despesa"/>

                        <CardImagemButton
                            link="/gestao-sgme/financeiro/contas-a-receber/cadastro"
                            img="/img/icone_venda.svg"
                            titleLink="Nova Despesa"/>

                    </div>

                    <div className="container d-sm-flex  align-items-center justify-content-between p-4">
                        <CardDashBoard total={totalReceitaMes}  valor={valorReceitaMes} tipo="receber"/>
                        <CardDashBoard total={totalDespesasMes}  valor={valorDespesaMes} tipo="pagar" />
                    </div>
                </section>
            </main>
        </>
    )
}
