import React, {useEffect, useState} from 'react';
import Link from "next/link";
import Head from "next/head";
import {http} from "@/utils/http";
import DespesaItem from "@/components/DespesaItem";
import Paginacao from "@/components/Paginacao";

function Index(props) {

    const [fornecedores, setFornecedores] = useState({});

    const [page, setPage] = useState(0);
    const [totalPages, setTotalPages] = useState(1);

    const [despesas, setDespesas] = useState([{
        fornecedor_id: '',
        valor: 0,
        data_vencimento: '',
        forma_pagamento: '',
        status: '',
    }]);

    useEffect(() => {
        http.get(`/despesas?page=${page}&size=10`,  { params: { page } })
            .then((response)=>{
                setDespesas(response.data.content)
                setTotalPages(response.data.totalPages)

            })
            .catch((err)=>{
                console.error("Erro ao buscar despesas" + err)
            })
    }, [page]);




    useEffect(() => {
        http.get(`/fornecedoresLista`)
            .then((response) => {
                const fornecedoresMap = response.data.reduce((map, fornecedor) => {
                    map[fornecedor.id] = fornecedor.nome;
                    return map;
                }, {});
                setFornecedores(fornecedoresMap);
            })
            .catch((error) => {
                console.error("Erro ao buscar lista de fornecedores:", error);
            });
    }, []);



    return (
        <>
            <Head>
                <title>SGME-Contas a pagar</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className="container">
                <div className="container d-sm-flex flex-row justify-content-between mb-3">
                    <h3>Contas a Pagar</h3>
                    <Link href="/gestao-sgme/financeiro/contas-a-pagar/cadastro" className="btn btn-success">Novo Conta
                        a Pagar</Link>
                </div>

                <table className="table">
                    <thead>
                    <tr className="border border-2 border-warning">
                        <th scope="col">Fornecedor</th>
                        <th scope="col">Valor</th>
                        <th scope="col" className="d-flex justify-content-end">Ações</th>

                    </tr>
                    </thead>
                    <tbody>

                    {despesas && despesas.length > 0 ? (
                        despesas.map(despesa => (
                            <DespesaItem key={despesa.id} despesa={despesa} fornecedores={fornecedores}/>
                        ))
                    ) : (
                        <tr>
                            <td colSpan="6">Nenhuma despesa encontrada.</td>
                        </tr>
                    )}

                    </tbody>


                </table>


                <Paginacao  page={page} totalPages={totalPages} setPage={setPage}/>


            </main>
        </>

    );
}

export default Index;