import React from 'react';
import Head from "next/head";

function Index(props) {
    return (
        <>
            <Head>
                <title>SGME-Perfil Usuario</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div className="container">
                <h1>
                    Perfil Usuario
                    <p>Pagina a ser implementada</p>
                </h1>
            </div>
        </>

    );
}

export default Index;