import React, {useState} from 'react';
import Head from "next/head";
import {useForm} from "react-hook-form";
import axios from "axios";
import {useRouter} from "next/router";
import {http} from "@/utils/http";
import ButtonFechar from "@/components/ButtonFechar";

function Cadastro(props) {
    const router = useRouter();
    const [errorApi, setErroApi] = useState(["OK"])
    const [resultErro, setResultErro] = useState(["OK"])
    const [status, setStatus] = useState([false])

    const {
        register,
        handleSubmit,
        formState: {errors},
        reset
    } = useForm();

    const onSubmit = async (data) => {

        try {
            await http.post(`/fornecedores`, data)
                .then((response) => {
                    setStatus(true)
                    reset()
                    router.push('/gestao-sgme/fornecedores')
                })
        } catch (error) {
            if (axios.isAxiosError(error) && error.response) {
                setErroApi(error.response.data.message)
                console.error('Erro na resposta da API', error.response.data)
            } else {
                console.error('Erro ao enviar dados para a API', error)
            }
        }
        setResultErro(errorApi.includes("Duplicate entry"));
    }


    return (
        <>
            <Head>
                <title>SGME - Cadastro de Fornecdores</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className="container d-flex align-items-center justify-content-center mt-5">

                <form className="form-control p-5">



                    <ButtonFechar url="gestao-sgme/fornecedores" />

                    <h3 className="mb-4">Novo Fornecedor</h3>
                    <div className="d-sm-flex flex-column  me-3">
                        <label htmlFor="valor">CPF/CNPJ: </label>
                        <input placeholder="CPF / Cnpj"
                               className="form-control"
                               {...register("codigo", {required: true})}
                        />
                        {errors?.codigo?.type === "required" && (
                            <p className="alert alert-danger mt-3">CPF obrigatorio!</p>
                        )}
                        {resultErro === true ? (
                            <p className="text-danger fw-bold">CPF / CNPJ já cadastrado</p>
                        ) : ("")}
                    </div>

                    <div className="d-flex flex-row justify-content-between mb-3">
                        <div className="d-flex flex-column w-100 me-3">
                            <label htmlFor="valor">Razao Social / Nome </label>
                            <input placeholder="Razao Social / Nome"
                                   className="form-control"
                                   {...register("nome", {required: true})}
                            />
                            {errors?.nome?.type === "required" && (
                                <p className="alert alert-danger mt-3">Nome é obrigatorio</p>
                            )}
                        </div>


                    </div>


                    <button className="btn btn-warning me-3" onClick={(e) => {
                        e.preventDefault();
                        handleSubmit(onSubmit)();
                    }}>SALVAR
                    </button>

                </form>
            </div>
        </>
    );
}

export default Cadastro;