import {useRouter} from "next/router";
import React, {useEffect, useState} from "react";
import axios from "axios";
import {url} from "@/utils/url";
import Head from "next/head";
import ButtonFechar from "@/components/ButtonFechar";

const UpdateFornecedor = () => {
    const router = useRouter();

    const {codigo} = router.query;


    const [fornecedor, setFornecedor] = useState(
        {
            codigo: "",
            nome: "",

        }
    );


    useEffect(() => {
        axios.get(`${url}/fornecedores/${codigo}`)
            .then((response) =>
                setFornecedor(response.data)
            )
            .catch((error) => {
                console.log("Erro ao buscar fornecedor" + error)
            })
    }, [codigo])

    const handleUpdateFornecedor = () => {
        axios
            .put(`${url}/fornecedores/${codigo}`, fornecedor)
            .then((response) => {
                alert("Fornecedor alterado com sucesso");
            })
            .catch((error) => {
                alert("Erro ao atualizar fornecedor:", error);
            });

        router.push('/gestao-sgme/fornecedores');
    };


    const handleInputChange = (e) => {
        setFornecedor({...fornecedor, [e.target.name]: e.target.value});
    };
    const handlerCancelar = () => {
        router.push('/gestao-sgme/fornecedores');
    }

    return (
        <>
            <Head>
                <title>SGME - Alterando Fornecedor</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>

            </Head>
            <div className="container d-flex align-items-center justify-content-center mt-5">

                <form className="form-control p-5">
                    <ButtonFechar url="/gestao-sgme/fornecedores"/>
                    <h3 className="mb-4">Atualizando Fornecedor</h3>
                    <div className="d-flex flex-column  me-3">
                        <label htmlFor="valor">Cpnj / CPF: </label>
                        <input placeholder="Cnpj / Cpf"
                               className="form-control"
                               name="codigo"
                               value={fornecedor.codigo}
                               onChange={handleInputChange}
                        />
                    </div>

                    <div className="d-flex flex-row justify-content-between mb-3">
                        <div className="d-flex flex-column w-100 me-3">
                            <label htmlFor="valor">Razão Social / Nome: </label>
                            <input placeholder="Razao Social / NOme"
                                   className="form-control"
                                   name="nome"
                                   value={fornecedor.nome}
                                   onChange={handleInputChange}
                            />

                        </div>


                    </div>

                    <button className="btn btn-success  me-3" onClick={handleUpdateFornecedor}>SALVAR</button>
                    <button className="btn btn-danger" onClick={handlerCancelar}>CANCELAR</button>

                </form>

            </div>
        </>
    )
}

export default UpdateFornecedor;